version: '3.3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso_spring
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
